// <auto-generated />
namespace Real_estate_business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Final : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Final));
        
        string IMigrationMetadata.Id
        {
            get { return "202010251754335_Final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
